Makefile
Like, udev rules and usb passthru script.
For udev rules, the idea is that a user will update repo's template with their
board serial number first.
=>  Makefile: Add "install" target to install host-side files. 

Makefile
The idea is that "lava-setup" target will do (semi-)automated setup of all things LAVA, though so far sets up just the user.
=>  Makefile: lava-setup: Automate setup of LAVA users. 

docker-compose.yaml, overlays/lava-common/usr/lib/python3/dist-packages/lava_common/schemas/boot/openocd.py, overlays/lava-common/usr/lib/python3/dist-packages/lava_common/utils.py, overlays/lava-dispatcher/usr/lib/python3/dist-packages/lava_dispatcher/actions/boot/openocd.py, overlays/lava-dispatcher/usr/lib/python3/dist-packages/lava_dispatcher/actions/boot/strategies.py, overlays/lava-server/etc/lava-server/dispatcher-config/device-types/cc3220SF.jinja2
This commit adds the OpenOCD boot action method as an overlay temporarily
til the change is merged into upstream LAVA.
Signed-off-by: Vincent Wan <vincent.wan@linaro.org>
=> docker-compose.yaml: Add overlays for OpenOCD boot action method

Makefile
Now that there's a need to stop udev-forward in addition to docker-compose.
=> Makefile: Add explicit "stop" target.

docker-compose.yaml
Add a few additional overlay sample lines to overlay a source tree into
the running image.  This is the easiest way to do development on the
lava source itself.
Signed-off-by: David Brown <david.brown@linaro.org>
=> docker-compose: Add overlay sample lines

contrib/board-setup-helper.py
All DAPLink firmwares starting from ~2015 have auto-reset off by default.
We agreed that we should default to support contemporary firmwares.
=> board-setup-helper.py: For frdm-k64f, use "resets_after_flash = false".

Makefile, device-types/musca_a.jinja2
This PR is supposed to supercede https://github.com/Linaro/lite-lava-docker-compose/pull/18 and lay the process for adding new device types to our setup in scalable manner.
=> Add musca_a device type

Makefile, contrib/make-board-files.sh
Based on board serials, stored in devices/<devname>.serial, create any
needed board configs, using board-setup-helper.py. The boards should be
connected to USB while running this.
=> Makefile: Add "board-configs" target.

Makefile, devices/docker-01.jinja2, docker-compose.yaml, example/docker-busybox.job
So we can use LAVA's docker support (run docker containers on dispatcher,
which in our setup itself runs on docker).
=> docker-compose.yaml: Allow to use docker inside lava-dispatcher.

Makefile, devices/qemu-zephyr-01.jinja2, example/micropython-interactive-qemu-zephyr.job
An example of making a LAVA QEMU device using QEMU binary at the specific
(non-default) location. This still tries to reuse LAVA's distribution
qemu.jinja2 template and override just required minimum in it (which is
still much, as entire QEMU command line needs to be costructed, but
definitely less than by copying the entire qemu.jinja2).
The device thus gets created with the standard "qemu" device type, but
when creating, it's assigned "qemu-zephyr" tag. Afterwards, this
device can be selected by a test job by adding following directives
to it:
tags:
- qemu-zephyr
=> devices/qemu-zephyr-01: QEMU device using Zephyr's QEMU.

example/docker-busybox.job
Previously, this job lacked "test" section, and this led to the fact
that the output could be either capture or not. Now add explicit
"test: monitor:" to consume (and effectively, check) the output,
making this a template for very simple, but a test.
=> example/docker-busybox: Actually consume and check output.

.env, lite-lava-dispatcher/Dockerfile
This is mostly a straightforward update, cherry-picking upstream commits. However, upstream docker images have upgraded to Debian Buster. It required updates to some package installed on our side.
I've tested this with example/ micropython-interactive.job, micropython-interactive-qemu-zephyr.job, lava.job (frdm_k64f), everything works as expected. Would be nice if other folks tested it with their boards/jobs.
=> Upgrade to Lava 2019.11

docker-compose.yaml
For a case of local development setup, we export ../lava/lava_common
because the common understanding was that it contains schemas used to
validate test action paramters across LAVA server/dispatcher boundary
(so, even if we mostly work on dispatcher changes, if we e.g. add new
action params, we must propagate schema changes back to server, or job
submissions with new params will be rejected).
However, turns out that LAVA has a technical debt due to which some of
job schemas are duplicated in ../lava/lava_scheduler_app. Upstream issue
https://git.lavasoftware.org/lava/lava/issues/358. Until it's fixed
(and it even was closed as "not a priority right now"), we need to
duplicate most of the schema changes to ../lava/lava_scheduler_app,
and export it to the container.
Signed-off-by: Paul …
=> docker-compose: lava-server: Bind ../lava/lava_scheduler_app

example/micropython-interactive.job
The previous URL expired, update it, so it was possible to quickly
uncomment it and submit against non-local server (e.g.
lite.validation.linaro.org).
=> example/micropython-interactive: Update download URLs.

example/micropython-interactive.job
"interactive" tests use pexpect, which in turn uses substring (actually,
regex search) matching. So, "4" would match any string with "4" inside,
e.g. "14", "41", etc. To match exactly "4", we must match also virtual
delimters, line end of lines, paying attention that pexpect matches
regexes "on streams" (not on finite strings), and thus standard regex
assertions like "^", "$" won't (necessarily) work as expected. Here,
we include explicit end-of-previous-line and end-of-this-line characters
(which are taken to be those output by micropython, and may potentially
be different with other software/hardware (e.g., with virual docker
devices)).
=> example/micropython-interactive: More precise response matches.

lite-lava-dispatcher/Dockerfile, lite-lava-dispatcher/lava-coordinator.sh
lava-coordinator should be run as a daemon for multinode jobs to work.
While its purpose is to allow (explicit) synchronization between sub-jobs
of a multinode job, it's connected to unconditionally for any multinode
job, and without it, such jobs will fail.
=> [WIP] lite-lava-dispatcher: Install and start lava-coordinator.

example/docker-xilinx-qemu-openamp-echo_test.job
Boots docker image, which boots contained qemu, then logs in and runs
OpenAMP's echo_test application using "interactive" test action.
Requires "echo: discard" support from LAVA 2019.12.
=> example: Add test job for OpenAMP echo_test using edmooring/qemu docker image

example/docker-xilinx-qemu-openamp-echo_test.job
Today LAVA is slow re: downloads. As this job wget's a test image during
runtime, no choice as to bump to the timeouts considerably.
=> example/docker-xilinx-qemu-openamp-echo_test: Bump timeouts to 10min.

Makefile
=> Makefile: Assign tags to docker devices, following lite.v.l.o.

lite-lava-dispatcher/Dockerfile
Because:
--2020-02-11 18:03:13--  https://www.segger.com/downloads/jlink/JLink_Linux_V650_x86_64.deb
Resolving www.segger.com (www.segger.com)... 78.31.67.95
Connecting to www.segger.com (www.segger.com)|78.31.67.95|:443... connected.
ERROR: cannot verify www.segger.com's certificate, issued by ‘CN=AlphaSSL CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE’:
Unable to locally verify the issuer's authority.
To connect to www.segger.com insecurely, use `--no-check-certificate'.
=> lite-lava-dispatcher/Dockerfile: Don't check cert when downloading JLink

docker-test-images/README.md, docker-test-images/xilinx-openamp-build/.dockerignore, docker-test-images/xilinx-openamp-build/Dockerfile, docker-test-images/xilinx-openamp-build/local.conf.append, docker-test-images/xilinx-openamp-build/run-yocto-build.sh, docker-test-images/xilinx-openamp-build/skip-FIGETBSZ.patch
Build an OpenAMP artifact (full-system SD card image) which can be submitted
to LAVA for testing.
=> docker-test-images/xilinx-openamp-build: Docker image to build OpenAMP

Makefile
The password prompt as it was before, didn't make clear whether it expects
some existing password, or a new password. Make it clear that it's the
latter case.
=> Makefile: lava-user: Better password prompt.

Makefile
For compatibility with lite.validation.linaro.org production site, where
only one of boards have networking setup. For local setup, we just mark
the only board with this tag for job definition compatbility.
The tag itself is consistent with a docker board tag added earlier.
=> Makefile: lava-boards: Add "zephyr-net" tag for frdm-k64f-01.

example/zephyr-net-ping-frdm_k64f.job
Switch to debian image instead of minimal busybox one, print local
network interface address to detect possible misconfig, update for
debian's ping output, select for test boards which have networking
access using tags.
=> zephyr-net-ping-frdm_k64f.job: Update for production usage.

example/zephyr-net-http-ab-frdm_k64f.job
Job to to run Apache Bench against dumb_http_server Zephyr sample. Requires
linaro-lava-net-test docker image.
=> example: Add zephyr-net-http-ab-frdm_k64f.job

docker-test-images/linaro-lava-net-test/Dockerfile, docker-test-images/linaro-lava-net-test/README
From README:
This directory contain definition for a "host" docker image used for
networking testing. It contains various networking tools and utilities
which are or can be useful for networking testing (not all tools
installed in the image may be used currently).
A testing process is usually comprised of a multinode LAVA job, where
this image is booted in a docker "virtual device", to represent a "host"
side of networking connection, and tools installed in the image are
used to access an embedded board as a "device under test" (or vice-versa,
for tests where host is a server and device is a client).
=> docker-test-images: Add "linaro-lava-net-test" test image.

example/zephyr-net-ping-frdm_k64f.job
Based on the idea that there should be a single full-featured docker
image for networking testing.
=> zephyr-net-ping-frdm_k64f: Switch to linaro-lava-net-test docker image

docker-test-images/linaro-lava-net-test/Dockerfile
Install Apache HTTP server and some other utils. Cache a test file
expected by big_http_download sample.
During work on this docker image, a severe slowness was detected,
the build process didn't complete in 30 mins, apparently hanging
while installing shared-mime-info package. The changes contain
workarounds for this (with them, the process completes in some
20 minutes, which is still *very* slow.)
This git pushed to DocketHub as pfalcon/linaro-lava-net-test:v2.
=> linaro-lava-net-test: Update image for big_http_download testing.

Makefile, devices/docker-01.jinja2
docker-01 is tagged as "zephyr-net", and intended to run host-side tools
useful for networking testing. One of such tools is an HTTP server, so
export container's HTTP port at host port 8980, so DUT can access it.
(Port number is chosen to not be commonly used "local development" port.)
=> devices/docker-01: Export HTTP port from container to host.

.env, overlays/lava-server/etc/apache2/sites-available/lava-server.conf
Cherry-picks of upstream commits.
As previously, this includes just those changes which cleanly cherry-pick to our branch (some commits change things not in our branch and were skipped).
=> Upgrade to LAVA 2020.04

example/zephyr-net-ping-frdm_k64f.job
The most interesting output in this job happens on host, so try to rearrange
it to go first in the sequence of multinode subjobs.
=> zephyr-net-ping-frdm_k64f.job: Define host first.

example/zephyr-net-http-ab-frdm_k64f.job
The most interesting output in this job happens on host, so try to rearrange
it to go first in the sequence of multinode subjobs.
This follows the change done previously to zephyr-net-ping-frdm_k64f.job.
=> zephyr-net-http-ab-frdm_k64f.job: Define host first.

Makefile
E.g., stop apache2 and ModemManager on Ubuntu.
=> Makefile: Add clean-env target to clean host environment for LAVA setup.

example/multinode-qemu-docker.job
This is very basic multinode job, intended to just check that multinode
works (and in this regard, similar to "micropython-interactive.job" aka
"make testjob"). It uses qemu and docker device types, and thus can run
without special hardware setup.
=> example/multinode-qemu-docker: Multinode test job.

Makefile, contrib/make-board-files.sh
'make board-configs' should backup any existing LAVA.rules file and
append to the file in case multiple boards are connected, otherwise
only the last one would appear in LAVA.rules.
Signed-off-by: Vincent Wan <vincent.wan@linaro.org>
=> Backup LAVA.rules and deal with multiple boards

contrib/board-setup-helper.py
Add cc3220SF and cc13x2-launchpad to 'make board-configs' of the automated setup flow.
In addition, fix contrib/board-setup-helper.py to handle these types of boards that expose multiple serial ports, so that a single connection_command is generated in the board file for the first port found.
Intended to be merged after #77.
=> Fix board-setup-helper.py to handle boards that expose multiple serial ports

Makefile
Start with creating "virtual" devices, like qemu and docker, then
create real boards. This is based on the idea that "real" devices
list will grow.
=> Makefile: lava-boards: Restructure device list.

Makefile
Previously used "dispatcher" is a historical quick/random name which
may lead to confusion: job submission and other lavacli oprations are
performed against server, not against a dispatcher. So, makes sense
to use names which don't contradict what actually happens.
=> Makefile: Use "lava-docker" as idenity name for lavacli.

devices/qemu-01.jinja2
This setting was made forward-looking to be able to use qemu for
networking testing. But we don't really use it for that, because
much more configuration would be need for that (and we didn't look
into it yet). But now, the 'tap' setting interferes with using
qemu-from-docker (it complains of missing /dev/net/tun), so disable
it for now, but keep around for when we'll look into it again.
Corresponds to production LAVA change
https://review.linaro.org/c/lava/lava-lab/+/35694
=> devices/qemu-01.jinja2: Don't set netdevice='tap' by default.

docker-compose.yaml
We need access to /run/udev for the docker test action.  This allows the
lava dispatcher to see the full udev info for a device.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
=> docker-compose: Expose more udev for docker test action

docker-compose.yaml
The lava-dispatcher code imports somethings from the lava_dispatcher_host
dir, so add it in as part of the dirs we would mount of we are pulling
in a development version of the lava-dispatcher.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
=> docker-compose: Add additional dir mount for lava-dispatcher for dev

contrib/board-setup-helper.py
We need device_info[].board_id set for use by docker test action.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
=> board-setup-helper.py: Add setting device_info

devices/qemu-zephyr-01.jinja2
This is similar to a change done previously qemu-01.jinja2, to make this
device compatible with qemu-from-docker usage. (This device isn't intended
for such a usage, but maybe randomly selected by scheduler nonetheless.
We'll need to use explicit tags going forward, but for now, this is
apparently a least-effort workaround.)
=> devices/qemu-zephyr-01.jinja2: Set netdevice to "user" for now.

Makefile, docker-compose.yaml
For some docker-in-docker scenarios (e.g. qemu-in-docker) sub-containers
needs to access downloaded images which are stored in tmp dir. Due to
the way docker-in-docker functionality works, it should be the same
bind mount across all containers (i.e. dispatcher container and
subcontainers spawned by it). And the way to achieve that is to mount
the same host path into the containers.
For more details, see upstream ticket:
https://git.lavasoftware.org/lava/pkg/docker-compose/-/issues/8
=> docker-compose.yaml: Mount dispatcher tmp dir for transitive access

Makefile
This was intended to be like that from the beginning, but instead turned
out to be duplicated, copy-pasted comment from the previous section in
the Makefile. Fix that now.
=> Makefile: lava-boards: Elaborate comment about hardware boards setup.

Makefile
Update lava-boards target to configure disco-l475-iot1
device.
Signed-off-by: Erwan GOURIOU <erwan.gouriou@linaro.org>
=> Makefile: add disco-l475-iot1 to lava-boards target

example/micropython-interactive-docker-qemu.job
This example is based on existing micropython-interactive.job, but utilizes
a recent LAVA feature - using QEMU binary from a Docker image (instead of
whatever binary is installed in the dispatcher).
(Besides pulling QEMU from Docker image, this sample also downloads test
binary from URL by default, to simplify testing against production LAVA,
and adjusts various timeouts, as pulling an image from Dockerhub takes
additional time).
=> examples: Add example for running QEMU from a Docker image.

Makefile
docker-compose and docker somehow use different namespaces for the names,
where docker's name is exact and concrete, while docker-compose name is
a logical name, from which a conrete is normally formed by namespacing
the logical name using a docker-compose project directory (so, there
potentially can be different deployments of the same project, residing
in different filesystem directories). It works that way, unless exact
docker name is explicitly overriden.
When we forked lava-docker-compose, it exactly used overriden names. But
later they were dropped. We however didn't (cherry-)pick that name, for
the fear that it may break our setup infra we built on top of the original
project.
So, if anything, this change brings us closer to the setup used in upstream
master, with the intention …
=> Makefile: Use "docker-compose exec" instead of "docker exec".

devices/qemu-01.jinja2, devices/qemu-zephyr-01.jinja2
Different QEMU machines, and applications running on them, have different
requirements regarding memory. So, don't hardcode a value in a device config,
and instead allow to specify a particular value in a job, in "context:"
dictionary. If none is specified, LAVA default of "512" will be used.
=> devices/qemu*: Don't hardcode "memory" parameter.

example/multinode-2-dockers-sync.job
This is a simple example job which shows how to use multinode
synchronization actions like "lava-send", "lava-wait" with
"interactive" tests, to coordinate actions between 2 devices.
This job requires just 2 "docker" virtual devices, so runs
without real hardware.
=> examples/multinode-2-dockers-sync.job: Example multinode sync job

example/zephyr-net-ping-frdm_k64f.job
Instead of having adhoc "sleep XX" in the test, switch to the proper
multinode synchronization: first, the "host" role waits for the "device"
role to boot, before starting to ping it. Then, "device" role waits
for "host" to complete its testing (before e.g. go offline).
Unfortunately, there's still a need to intersperse adhoc delays for
longer multinode syn operation, because default multinode operation
timeout is pretty small (30s), and there's no visible way to adjust
it.
=> zephyr-net-ping-frdm_k64f.job: Switch to multinode synchronization

example/zephyr-net-http-ab-frdm_k64f.job
Following similar conversion done to zephyr-net-ping-frdm_k64f.job.
=> zephyr-net-http-ab-frdm_k64f.job: Switch to multinode sync.

Makefile
When we set a template for custom device type with
"lavacli device-types template set" command, it ends up in one container
on docker-compose system, but actually also expected in others. This is
a known upstream issue tracked as
https://git.lavasoftware.org/lava/pkg/docker-compose/-/issues/4.
We work it around for now by pushing the file manually to "another"
container. Currently, this applies to "musca_a" device type, but care
should be taken to apply the same workaround to other introduced custom
device types.
=> Makefile: Add a workaround for deploying custom device type

Makefile
Similar to a change previously in another place. Allows us to rely on
docker-compose's logical names (and ultimately, get close to upstream
and run multiple instances of the setup).
=> Makefile: *-shell: Use "docker-compose exec" instead of "docker exec".

example/zephyr-net-http-ab-frdm_k64f.job, example/zephyr-net-ping-frdm_k64f.job
The underlying issue with too short, non-adjustastable timeout for
"lava-wait" (https://git.lavasoftware.org/lava/lava/-/issues/429)
was fixed in LAVA 2020.08.
=> example/zephyr-net-*: Remove "delay" workarounds.

contrib/usb-passthrough
Updates to usb-passthrough script to match the set of devices expected by lava docker action.
The lava code uses pyudev to determine what device nodes should be passed to a container.  We need to pass the same set of device nodes in usb-passthrough so we match the logic there.
=> Usb passthrough

example/lava.job
The test pattern on which we actually relied was "BOOTING ZEPHYR OS",
but quite some time ago that was changed upstream to "Booting Zephyr OS".
In this case, other start patterns matched, but the whole matching
was mis-synchronized, e.g. individual testcases weren't matched properly.
The whole match patterns need to be cleaned up, but that should be done
in concert with production CI patterns, so for now just apply quick fix.
=> example/lava.job: Update test start pattern

Makefile
LAVA worker name changes with 2020.09 upgrade. To reduce upgrade delta
(which is already non-trivial) and faciliate review, factor out worker
name as a config option ahead of the upgrade.
=> Makefile: Add LAVA_WORKER setting.

lite-lava-dispatcher/Dockerfile
Update jlink to 6.88a and zephyr-sdk to 0.11.4
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
=> lite-lava-dispatcher: bump tool version

example/micropython-interactive-docker-qemu.job
Artifacts hosted on snapshots.linaro.org expire eventually, so switch the
file to local binary, like other micropython-interactive* jobs.
Also, set jobname to match the filename exactly, so it was easier to relate
job result list in LAVA to the actual job defs.
=> example/micropython-interactive-docker-qemu: Use local binary.

example/micropython-interactive-qemu-zephyr.job, example/micropython-interactive.job
This follows https://github.com/Linaro/lite-lava-docker-compose/pull/124, and roughly follows naming of other jobs.
The motivation is batch-style "sanity check", where a bunch of jobs are submitted at once, so it was clear which job is which.
=> example/micropython-interactive*: Make jobname match filename

example/multinode-2-dockers-sync.job, example/multinode-qemu-docker.job
These test can run on overloaded systems, and also Docker itself is known
to haev episodes of explainable slow performance, where systems is seemingly
not overloaded, but things in containers run slower than usual.
=> example/multinode-*: Increase timeout.

example/zephyr-net-big_http_download-frdm_k64f.job, example/zephyr-net-http-ab-frdm_k64f.job, example/zephyr-net-ping-frdm_k64f.job
Serveral initial characters after booting a board may come in garbled. So,
avoid matching by the "Booting Zephyr ..." content, match by "ng Zephyr ...".
Also, match until the end of line, this leads to more logical log output
(first device input is shown, and then "prompt" matched message, and not
vice-versa).
=> example/zephyr-net-*: More reliably match Zephyr "booting" line.

docker-compose.yaml
5000-5099 is 100 ports, and that range can be occupied by other services
on localhost. For example, 5037 is the default port for Android adbd.
The larger the range, the higher chance of conflict. 10 ports/devices
should be more than enough for a typical local LAVA deployment. (And
if more needed, that can be extended as part of private config, similar
to board serials, etc.)
=> docker-compose.yaml: ser2net: Reduce port range exported to the host.

Makefile
As we now have a common LAVA Lab system, validation.linaro.org, which has
many QEMU devices, we need to disambiguate specifically our, LITE devices,
which have special config options (in the device dicts). This is now done
using "lite" device tags. So, propagate this change back to local Docker
setup for compatibility.
=> Makefile: lava-boards: Set "lite" label to qemu-* devices.

example/tfm-regression-qemu.job
SQUAD cannot handle duplicate testcase names (while LAVA can),
https://github.com/Linaro/squad/issues/925. An easy fix would be to
switch to use TF-M's testcase IDs as LAVA testcase names, but those
aren't human-readable, so seeing a testcase (among ~170 other) won't
tell you much without digging into source code. So, we hold onto
keeping human-readable description, and capture both, even though that
makes the testcase longish, with a static word "description" repeated
thru each. An example of a testcase name now:
tfm_sst_test_2009_description_get_interface_with_invalid_data_lengths_and_offsets
Thanks to Milosz Wasilewski for suggesting this approach.
=> tfm-regression-qemu.job: Capture both unique test ID and description

example/micropython-interactive.job
All binary builds eventually expire are garbage-collected. So, just use
"latest" link instead. (A minor risk is that the latest binary may be
broken, the whole idea of using a specific build was that it was actually
tested to work. But there's always some drawbacks, one way ot another.)
=> micropython-interactive.job: Reference non-expiring binary link.

example/lava.job
This change depends on the cmsis-dap boot action to detect failure
(flashing failure, to be specific). Currently LAVA doesn't do, but
the patch was submitted to do that:
https://git.lavasoftware.org/lava/lava/-/merge_requests/1416
So, proactively add this setting, so it wasn't forgotten later.
=> example/lava.job: boot: cmsis-dap: Add "failure_retry: 3".

Makefile
systemd manages to error out on "restart" if the service is not running.
=> Makefile: ser2net-raspi: Stop, then start ser2net service.

example/zephyr-net-big_http_download-frdm_k64f.job, example/zephyr-net-http-ab-frdm_k64f.job, example/zephyr-net-ping-frdm_k64f.job
=> example/zephyr-net-*.job: Use "failure_retry: 3".

Makefile
Similar to existing frdm-k64f-01, etc. Actual device configs should be
made by a user.
=> Makefile: lava-boards: Add frdm-kw41z-01 device.

example/zephyr-net-http-ab-frdm_k64f.job, example/zephyr-net-ping-frdm_k64f.job
These jobs are used as templates for production zephyr-net CI job, and
current target board (lite-frdm-k64f-02) is flaky with "cmsis-dap" boot
method, in less so with "pyocd".
=> example/zephyr-net-*.job: Switch to pyocd boot method.

example/zephyr-net-ping-frdm_k64f.job
Test includes multinode sync, which may take extra time depending on the
other node's job.
Case seen: https://validation.linaro.org/scheduler/job/2409329
=> zephyr-net-ping-frdm_k64f.job: Bump test timeout to 90s

lite-lava-dispatcher/Dockerfile
0.30 made incompatible changes to executables names, and so device configs
shipped with LAVA aren't compatible with it. The patch to upgraded LAVA
config was posted: https://git.lavasoftware.org/lava/lava/-/merge_requests/1481
But until it's merged, let's still to the last version supported OOB.
=> lite-lava-dispatcher/Dockerfile: Pin pyocd to 0.29.0.

device-types/staging.validation.linaro.org/lpcxpresso55s69.jinja2, device-types/validation.linaro.org/frdm-k64f.jinja2
Recently, we've got a need to change device type template in the Lab beyond what's shipped in LAVA releases. These changes either specific to peculiar hardware combinations/issues happening in the Lab, or something which isn't practical to propagate to the LAVA distribution at this time: https://git.lavasoftware.org/lava/lava/-/merge_requests/1481
Ideally, such changes should be tracked via Lab's configuration management system, but I may imagine it may take some time to setup that process, and some changes are experimental (cancelled or flip-flopping) anyway. But given that we have 2nd change like that, I'd like them to be captured and visible via change management process, even via interim solution.
To not create yet another repo which will be forgotten and hard to find later, I propose …
=> Store original and changed device types in the Linaro LAVA Lab
